
services:

  wordpress:
    image: docker.io/library/wordpress:6.9.1
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - /var/data/wordpress/content:/var/www/html
    ports:
      - 8090:80

  db:
    image: docker.io/library/mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - /var/data/wordpress/mysql:/var/lib/mysql
