---
- name: provision vagrant box
  hosts: all
  gather_facts: no
  become: yes

  tasks:

    - name: Set timezone
      ansible.builtin.command: "timedatectl set-timezone Europe/Berlin"

    - name: Install packages
      ansible.builtin.apt:
        name:
          - podman
          - podman-compose
          - vim
          - jq
        update_cache: yes

    - name: Remove other motds
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_fileglob: "/etc/update-motd.d/??-[!w]*"

    - name: Remove default motd
      ansible.builtin.copy:
        src: /dev/null
        dest: /etc/motd

    - name: Set message of the day
      ansible.builtin.copy:
        src: ./motd
        dest: /etc/update-motd.d/00-welcome
        owner: root
        group: root
        mode: '0755'

    - name: Set podman search registries
      ansible.builtin.lineinfile:
        path: /etc/containers/registries.conf
        regexp: '^unqualified-search-registries ='
        line: 'unqualified-search-registries = ["docker.io", "container-registry.oracle.com"]'

    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
        owner: vagrant
        group: vagrant
      with_items:
        - /var/data/postgres
        - /var/data/mysql
        - /var/data/oracle
        - /var/data/wordpress/content
        - /var/data/wordpress/mysql

    - name: Set owner of mysql data directory
      ansible.builtin.command: "podman unshare chown 999:999 {{ item }}"
      become_user: vagrant
      with_items:
        - /var/data/mysql
        - /var/data/wordpress/mysql

    - name: Set owner of oracle data directory
      ansible.builtin.command: "podman unshare chown 54321:54321 /var/data/oracle"
      become_user: vagrant

    - name: Set owner of wordpress content directory
      ansible.builtin.command: "podman unshare chown 33:33 /var/data/wordpress/content"
      become_user: vagrant
